import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../styles/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  title: { ...typography.h1, fontSize: 20 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: spacing.small,
    marginHorizontal: spacing.medium,
    marginTop: spacing.medium,
    paddingLeft: spacing.medium,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: { marginRight: spacing.small },
  searchInput: { flex: 1, height: 40, fontSize: 16 },
  filterButton: { padding: spacing.small },
  filtersPanel: {
    paddingVertical: spacing.small,
    backgroundColor: '#fdfdfd',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  filterTitle: {
    ...typography.body,
    fontWeight: 'bold',
    marginLeft: spacing.medium,
    marginTop: spacing.small,
    color: colors.textSecondary,
  },
  filterScrollView: {
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
  },
  chip: {
    backgroundColor: colors.white,
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.small,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.primary },
  chipTextActive: { color: colors.white },
  emptyText: { ...typography.body, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.xlarge },
  card: {
    backgroundColor: colors.white,
    padding: spacing.medium,
    marginVertical: spacing.small,
    marginHorizontal: spacing.medium,
    borderRadius: spacing.small,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardSelected: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: '#E7F0FE',
  },
  questionText: { ...typography.body, fontWeight: 'bold', marginBottom: spacing.small },
  footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  detailsText: { ...typography.caption },
  confirmButtonContainer: {
    padding: spacing.medium,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
});