// Local: Mobile/eduplan/screens/QuestionBankScreen/QuestionBankScreen.js

import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../styles/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  backButton: {
    paddingRight: spacing.small,
  },
  title: {
    ...typography.h1,
    fontSize: 20,
    textAlign: 'center',
    flex: 1,
    marginHorizontal: spacing.small,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: spacing.small,
    marginHorizontal: spacing.medium,
    marginTop: spacing.medium,
    paddingLeft: spacing.medium,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: { marginRight: spacing.small },
  searchInput: { flex: 1, height: 40, fontSize: 16 },
  filterButton: {
    padding: spacing.small,
  },
  filtersPanel: {
    paddingVertical: spacing.small,
    paddingHorizontal: 0,
    backgroundColor: '#fdfdfd',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  filterTitle: {
    ...typography.body,
    fontWeight: 'bold',
    marginLeft: spacing.medium,
    marginTop: spacing.small,
    color: colors.textSecondary,
  },
  filterScrollView: {
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
  },
  chip: {
    backgroundColor: colors.white,
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.small,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: { color: colors.primary },
  chipTextActive: { color: colors.white },
  emptyText: { ...typography.body, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.xlarge },
  card: {
    backgroundColor: colors.white,
    padding: spacing.medium,
    marginVertical: spacing.small,
    marginHorizontal: spacing.medium,
    borderRadius: spacing.small,
    borderWidth: 1,
    borderColor: colors.border,
  },
  favoriteButton: { // Estilo para o botão de favorito
    position: 'absolute',
    top: spacing.small,
    right: spacing.small,
    padding: spacing.small / 2,
    zIndex: 1,
  },
  questionText: {
    ...typography.body,
    fontWeight: 'bold',
    marginBottom: spacing.small,
    marginRight: 30, // Espaço para o botão de favorito não sobrepor
  },
  footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  detailsText: { ...typography.caption },
  canonicalText: {
    ...typography.caption,
    fontWeight: 'bold',
    color: colors.success,
    backgroundColor: '#E8F5E9',
    paddingVertical: 2,
    paddingHorizontal: spacing.small,
    borderRadius: spacing.small,
    overflow: 'hidden',
  },
  fab: {
    position: 'absolute',
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    right: spacing.large,
    bottom: spacing.large,
    backgroundColor: colors.primary,
    borderRadius: 28,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});